import = ["~/.config/alacritty/themes/catppuccin-mocha.toml",]

[env]
TERM = "alacritty"

[window]
decorations       = "None"
resize_increments = true
startup_mode      = "Maximized"

[window.padding]
x = 10
y = 0

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "Never"

[cursor.vi_mode_style]
blinking = "Always"

[mouse]
hide_when_typing = true

[hints]
alphabet = "ntesirlpufywhdcxmgoakvqzjb"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key    = "ArrowDown"
mods   = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key    = "ArrowUp"
mods   = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key    = "Escape"
mode   = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key    = "N"
mods   = "Shift"
mode   = "Search"
