# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  pagers:
    - # colorArg: always
      externalDiffCommand: difft --color=always --display=inline
      # pager: delta --dark --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#6c7086'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#b4befe'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
    inactiveViewSelectedLineBgColor:
      - '#1e1e2e'
    markedBaseCommitFgColor:
      - '#11111b'
    markedBaseCommitBgColor:
      - '#89dceb'
  authorColors:
    '*': '#b4befe'
  nerdFontsVersion: "3"
  showFileIcons: false
